### ISSUE TITLE
Uncaught TypeError: Cannot read property 'start' of null

### ISSUE THREAD

**Issue by nscaife** [gepoch/linter-write-good#8]
**Atom Version**: 0.202.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [linter](https://github.com/AtomLinter/Linter) package, v0.12.6

### Stack Trace

Uncaught TypeError: Cannot read property 'start' of null

```
At C:\Users\Nolen\AppData\Local\atom\app-0.202.0\resources\app.asar\node_modules\text-buffer\lib\range.js:35

TypeError: Cannot read property 'start' of null
  at Function.module.exports.Range.fromObject (C:\Users\Nolen\AppData\Local\atom\app-0.202.0\resources\app.asar\node_modules\text-buffer\lib\range.js:35:31)
  at TextBuffer.module.exports.TextBuffer.clipRange (C:\Users\Nolen\AppData\Local\atom\app-0.202.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:980:21)
  at TextBuffer.module.exports.TextBuffer.markRange (C:\Users\Nolen\AppData\Local\atom\app-0.202.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:672:46)
  at DisplayBuffer.module.exports.DisplayBuffer.markBufferRange (C:\Users\Nolen\AppData\Local\atom\app-0.202.0\resources\app.asar\src\display-buffer.js:1297:41)
  at TextEditor.module.exports.TextEditor.markBufferRange (C:\Users\Nolen\AppData\Local\atom\app-0.202.0\resources\app.asar\src\text-editor.js:1249:59)
  at LinterView.createMarker (C:\Users\Nolen\.atom\packages\linter\lib\linter-view.coffee:190:22)
  at LinterView.display (C:\Users\Nolen\.atom\packages\linter\lib\linter-view.coffee:227:17)
  at LinterView.processMessage (C:\Users\Nolen\.atom\packages\linter\lib\linter-view.coffee:178:8)
  at LinterView.processMessage (C:\Users\Nolen\.atom\packages\linter\lib\linter-view.coffee:1:1)
  at C:\Users\Nolen\.atom\packages\linter\lib\linter-view.coffee:164:14
  at LinterWriteGood.processMessage (C:\Users\Nolen\.atom\packages\linter-write-good\lib\linter-write-good.coffee:50:5)
  at C:\Users\Nolen\.atom\packages\linter\lib\linter.coffee:173:8
  at triggerExitCallback (C:\Users\Nolen\AppData\Local\atom\app-0.202.0\resources\app.asar\src\buffered-process.js:213:47)
  at C:\Users\Nolen\AppData\Local\atom\app-0.202.0\resources\app.asar\src\buffered-process.js:227:18
  at Socket.<anonymous> (C:\Users\Nolen\AppData\Local\atom\app-0.202.0\resources\app.asar\src\buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```

### Commands

```
  7x -0:45.9.0 core:select-right (atom-text-editor.editor.is-focused)
     -0:44.8.0 core:select-left (atom-text-editor.editor.is-focused)
  9x -0:43.1.0 core:move-down (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -0:39.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:38.3.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:36.8.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:36.5.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:36 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
 69x -0:35.5.0 core:move-right (atom-text-editor.editor.is-focused)
 31x -0:31.9.0 core:select-left (atom-text-editor.editor.is-focused)
     -0:14.9.0 core:move-right (atom-text-editor.editor.is-focused)
 19x -0:14.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:09.9.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
  2x -0:09.6.0 core:delete (atom-text-editor.editor.is-focused)
     -0:08.1.0 core:save (atom-text-editor.editor.is-focused)
     -0:07.1.0 latex:build (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "jekyll"
    ]
  },
  "linter": {}
}
```

### Installed Packages

```coffee
# User
atom-pair, v1.1.6
column-select, v0.2.0
file-icons, v1.5.5
git-tab-status, v1.9.2
language-latex, v0.6.1
language-reg, v0.0.0
latex, v0.24.0
linter, v0.12.6
linter-chktex, v0.3.0
linter-write-good, v0.4.3
minimap, v4.9.0
pdf-view, v0.22.0
script, v2.23.0
symbols-tree-view, v0.9.3
wordcount, v2.2.2

# Dev
latex, v0.23.4
linter-chktex, v0.3.0
```

**Comment by nscaife** [comment]
Reporting this here because a similar reported issue on Linter turned out to be the plugin and not Linter.

**Comment by gepoch** [comment]
@nscalfe there's been a pretty major rewrite to comply with the new linter API. I'm unable to reproduce this issue. Let me know if you see it again!
